apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votingapp
  template:
    metadata:
      labels:
        app: votingapp
    spec:
      containers:
        - name: votingapp
          image: <+artifact.image>
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: votingapp-svc
spec:
  selector:
    app: votingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
